version: '3'
services:
  rexuiz:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - WHITELIST_ENABLED=false
    volumes:
      - ./config:/home/rexuiz/.rexuiz/data
    ports:
      - "26000:26000/udp"
